spring.application.name=booking

spring.datasource.url=jdbc:postgresql://localhost:5432/BeautyService
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
security.jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUQXV0aEZvckJvb2tpbmdBcHAxMjM0NQ==
security.jwt.expiration-ms=86400000
